shared:
  languages:
    - :fr
    - :en

  assessment_types:
    - fr: :Interne
      en: :Internal
    - fr: :Externe
      en: :External
    - fr: :Web
      en: :Web
    - fr: :Phishing
      en: :Phishing

  finding_types:
    - fr: :Injection
      en: :Injection
    - fr: :Autorisation
      en: :Authorization
    - fr: :Gestion des mots de passe
      en: :Password management

  hacker_profiles:
    - fr: :Débutant
      en: :Beginner
    - fr: :Novice
      en: :Intermediate
    - fr: :Expert
      en: :Expert
    - fr: :Mercenaire
      en: :Mercenary

  remediation_effort:
    - fr: :Simple
      en: :Quick
    - fr: :Intermédiaire
      en: :Intermediate
    - fr: :Complexe
      en: :Complex
